---
- name: Apply Ansible Playbook to Vagrant VMs
  hosts: all
  become: true
  tasks:
    - name: Ensure SSH key is present
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      register: ssh_key_results
    - name: open dir
      raw: echo hello > hello.txt
      
