load "/home/audmas/Desktop/app1/app1-rework/provision_cumulus.rb"
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "CumulusCommunity/cumulus-vx"
  c.vm.box_version = "4.3.0"
  c.vm.hostname = "r1-cumulus.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-app1-rework-r1-cumulus-4ee245d3-906c-49ff-aa79-93de8b16f6cf"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
