load "/home/audmas/Desktop/zzz/provision_cumulus.rb"
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "CumulusCommunity/cumulus-vx"
  c.vm.box_version = "4.3.0"
  c.vm.hostname = "r1-cumulus.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-zzz-r1-cumulus-a259f543-d24d-423e-9b5e-688e7d2e2cc0"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
