driver:
  name: vagrant

platforms:
  - name: cumulus
    driver:
      box: "CumulusCommunity/cumulus-vx"
      box_version: "4.3.0"
      provision: true
      vagrantfiles: ['provision_cumulus.rb']

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  hosts: all
  require_ansible_repo: false

verifier:
  name: serverspec

suites:
  - name: r1
    provisioner:
      playbook: r1.yml
    verifier:
      default_pattern: no
      patterns:
        - roles/app1-rework/test/integration/default/test1_spec.rb
      rspec_path: '/usr/local/bin'

  - name: r2
    provisioner:
      playbook: r2.yml
    verifier:
      default_pattern: no
      patterns:
        - roles/app1-rework/test/integration/default/test2_spec.rb
      rspec_path: '/usr/local/bin'
