load "/home/audmas/Desktop/app1/app1-rework/provision_cumulus.rb"
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "CumulusCommunity/cumulus-vx"
  c.vm.box_version = "4.3.0"
  c.vm.hostname = "r2-cumulus.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-app1-rework-r2-cumulus-91d41426-da8a-4407-8627-ac1d908f115d"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
