load "/home/audmas/Desktop/zzz/provision_cumulus.rb"
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "CumulusCommunity/cumulus-vx"
  c.vm.box_version = "4.3.0"
  c.vm.hostname = "r1-r1.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-zzz-r1-r1-6cb9e1e2-0f31-427d-92e2-368fb5164b99"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
